In [1]:
import pandas as pd

**Cargar datasets**

In [2]:
url_clientes = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/clientes.csv"
url_aseguradoras = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/aseguradoras.csv"
url_corredores = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/corredores.csv"
url_tipos = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"
url_polizas = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/polizas.csv"
url_siniestros = "https://raw.githubusercontent.com/kevinnumanzor17/etl-seguros-pipeline/refs/heads/main/data/raw/siniestros.csv"

In [3]:
clientes = pd.read_csv(url_clientes)
aseguradoras = pd.read_csv(url_aseguradoras)
corredores = pd.read_csv(url_corredores)
tipos_seguro = pd.read_csv(url_tipos)
polizas = pd.read_csv(url_polizas)
siniestros = pd.read_csv(url_siniestros)

**Verificar que funcionó**

In [4]:
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [5]:
clientes.shape

(3030, 7)

**Exploración de datos**

In [6]:
clientes.info()
aseguradoras.info()
corredores.info()
tipos_seguro.info()
polizas.info()
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

In [7]:
clientes.isnull().sum()

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

**Limpieza general de datos**

In [8]:
def limpiar_dataframe(df):
    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)
    df = df.drop_duplicates()

    return df

In [9]:
clientes = limpiar_dataframe(clientes)
aseguradoras = limpiar_dataframe(aseguradoras)
corredores = limpiar_dataframe(corredores)
tipos_seguro = limpiar_dataframe(tipos_seguro)
polizas = limpiar_dataframe(polizas)
siniestros = limpiar_dataframe(siniestros)

**Transformaciones importantes**

In [10]:
polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')

siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'], errors='coerce'
)

polizas['prima'] = polizas['prima'].astype(str).str.replace(",", ".")
polizas['comision'] = polizas['comision'].astype(str).str.replace(",", ".")
polizas['monto_asegurado'] = polizas['monto_asegurado'].astype(str).str.replace(",", ".")

polizas['prima'] = pd.to_numeric(polizas['prima'], errors='coerce')
polizas['comision'] = pd.to_numeric(polizas['comision'], errors='coerce')
polizas['monto_asegurado'] = pd.to_numeric(polizas['monto_asegurado'], errors='coerce')

/tmp/ipykernel_243/847795375.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(

**Exportar archivos curated**

In [11]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    4522 non-null   datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            15050 non-null  float64
 7   comision         19861 non-null  float64
 8   monto_asegurado  10185 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

In [12]:
clientes.to_csv("clientes_curated.csv", index=False)
aseguradoras.to_csv("aseguradoras_curated.csv", index=False)
corredores.to_csv("corredores_curated.csv", index=False)
tipos_seguro.to_csv("tipos_seguro_curated.csv", index=False)
polizas.to_csv("polizas_curated.csv", index=False)
siniestros.to_csv("siniestros_curated.csv", index=False)

In [13]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 42.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [14]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16")

In [15]:
engine.connect()

Establecer conexion a la base

In [16]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [17]:
import pandas as pd
from sqlalchemy import create_engine

In [18]:
DATABASE_URL = "postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16"

engine = create_engine(DATABASE_URL)

In [19]:
engine.connect()

In [20]:
pd.read_sql("SELECT version();", engine)

                                             version
0  PostgreSQL 17.9 (Debian 17.9-1.pgdg12+1) on x8...

**CREAR TABLAS SQL**

In [34]:
clientes.to_sql('clientes', engine, if_exists='replace', index=False)
aseguradoras.to_sql('aseguradoras', engine, if_exists='replace', index=False)
corredores.to_sql('corredores', engine, if_exists='replace', index=False)
tipos_seguro.to_sql('tipos_seguro', engine, if_exists='replace', index=False)
polizas.to_sql('polizas', engine, if_exists='replace', index=False)
siniestros.to_sql('siniestros', engine, if_exists='replace', index=False)

print("Tablas creadas y datos cargados")

Tablas creadas y datos cargados

In [35]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'
""", engine)

         table_name
0  clientes_curated
1  clientes_rejects
2        corredores
3          clientes
4      aseguradoras
5      tipos_seguro
6           polizas
7        siniestros

In [36]:
pd.read_sql("SELECT COUNT(*) FROM clientes", engine)

   count
0   3030

In [37]:
pd.read_sql("SELECT * FROM clientes LIMIT 5", engine)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,nan
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,nan,01-02-80,Sta. Ana,nan
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,nan
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,nan,1945/08/02,San Salvador,Pyme

**verificar registros**

In [38]:
pd.read_sql("SELECT COUNT(*) FROM clientes", engine)

   count
0   3030

In [39]:
pd.read_sql("SELECT COUNT(*) FROM aseguradoras", engine)

   count
0     15

In [40]:
pd.read_sql("SELECT COUNT(*) FROM corredores", engine)

   count
0     80

In [41]:
pd.read_sql("SELECT COUNT(*) FROM tipos_seguro", engine)

   count
0     12

In [42]:
pd.read_sql("SELECT COUNT(*) FROM polizas", engine)

   count
0  25150

In [43]:
pd.read_sql("SELECT COUNT(*) FROM siniestros", engine)

   count
0   4620

In [44]:
pd.read_sql("SELECT * FROM clientes LIMIT 5", engine)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,nan
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,nan,01-02-80,Sta. Ana,nan
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,nan
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,nan,1945/08/02,San Salvador,Pyme

In [45]:
pd.read_sql("SELECT * FROM polizas LIMIT 5", engine)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,139253.11
1,2,2026-02-16,2408,35,11,12,NaN,12.22,NaN
2,3,NaT,540,42,4,9,1611.53,92.05,NaN
3,4,NaT,2821,40,10,5,1866.62,456.99,244461.27
4,5,NaT,945,23,9,11,NaN,324.08,123407.75

In [46]:
pd.read_sql("""
SELECT
c.nombre,
p.id_poliza,
p.monto_asegurado,
s.monto_siniestro
FROM polizas p
LEFT JOIN clientes c
ON p.id_cliente = c.id_cliente
LEFT JOIN siniestros s
ON p.id_poliza = s.id_poliza
LIMIT 10
""", engine)

                      nombre  id_poliza  monto_asegurado monto_siniestro
0  Fernanda Ramírez Martínez          1        139253.11            None
1      Carlos Aguilar García          2              NaN            None
2         Lucía Gómez Torres          3              NaN        3,842.84
3        Karla López Vásquez          4        244461.27            None
4        José Morales Flores          5        123407.75            None
5          Paula Rojas Ortiz          6         71968.43            None
6          Daniela Cruz Cruz          7        258202.93            None
7       Carlos Ramírez Ortiz          8              NaN            None
8         Ricardo Cruz López          9        125804.84            None
9        Karla Rojas Morales         10         20710.00            None

In [47]:
pd.read_sql("SELECT COUNT(*) AS total_polizas FROM polizas", engine)

   total_polizas
0          25150

In [49]:
pd.read_sql("""
SELECT estado, COUNT(*)
FROM siniestros
GROUP BY estado
""", engine)

      estado  count
0  Rechazado    636
1    Cerrado    645
2        nan   1298
3    ABIERTO    664
4    cerrado    677
5    Abierto    700

**Consultas SQL del analisis**

total de clientes

In [52]:
pd.read_sql("""
SELECT COUNT(*) AS total_clientes
FROM clientes
""", engine)

   total_clientes
0            3030

Total de pólizas emitidas

In [53]:
pd.read_sql("""
SELECT COUNT(*) AS total_polizas
FROM polizas
""", engine)

   total_polizas
0          25150

Monto total asegurado

In [54]:
pd.read_sql("""
SELECT SUM(monto_asegurado) AS total_monto_asegurado
FROM polizas
""", engine)

   total_monto_asegurado
0           1.147517e+09

Pólizas por tipo de seguro

In [55]:
pd.read_sql("""
SELECT
ts.tipo,
COUNT(p.id_poliza) AS total_polizas
FROM polizas p
JOIN tipos_seguro ts
ON p.id_tipo_seguro = ts.id_tipo_seguro
GROUP BY ts.tipo
ORDER BY total_polizas DESC
""", engine)

         tipo  total_polizas
0  Industrial           8296
1        Auto           4271
2    Agrícola           2168
3        Pyme           2126
4      Dental           2102
5  Accidentes           2088
6   Educación           2070
7       Salud           2029

Total de siniestros por estado

In [56]:
pd.read_sql("""
SELECT
estado,
COUNT(*) AS total_siniestros
FROM siniestros
GROUP BY estado
""", engine)

      estado  total_siniestros
0  Rechazado               636
1    Cerrado               645
2        nan              1298
3    ABIERTO               664
4    cerrado               677
5    Abierto               700